# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.045},
    {id: 1, size: 0.045},
    {id: 2, size: 0.045},
    {id: 3, size: 0.045},
    {id: 4, size: 0.045},
    {id: 5, size: 0.045},
    {id: 6, size: 0.045},
    {id: 7, size: 0.045},
    {id: 8, size: 0.045},
    {id: 9, size: 0.045},
    {id: 10, size: 0.045},
    {id: 11, size: 0.045},
    {id: 581, size: 0.14},
    {id: 582, size: 0.14},
    # {id: 583, size: 0.096},
    # {id: 584, size: 0.096},
    # {id: 585, size: 0.096},
    # {id: 586, size: 0.096},
  ]
tag_bundles: []